
tasks:
  - name: Setup, Install & Build
    init: npm install
    command: npm install
  - name: Install Sass
    init: npm install sass -g
    command: npm install sass -g

# Ports to expose on workspace startup
ports:
    - port: 3000
      onOpen: open-preview
      name: Website
      description: Website Preview
      visibility: private
      protocol: https

vscode:
  extensions:
    - oorzc.scss-to-css-compile
